# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Is manager?')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'verbose_name': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(default=False, verbose_name='Description')),
                ('due_date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Due date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'verbose_name': 'Task',
            },
        ),
    ]
