# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(default=False, verbose_name='Description')),
                ('due_date', models.DateField(default=datetime.datetime.today, verbose_name='Due date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create time')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Is manager?')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(to='application.User'),
        ),
    ]
