# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170225_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Due date'),
        ),
    ]
