export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
export const DELETE_ITEM = 'DELETE_USER';
export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM';
export const UPDATE_ITEM_SETTINGS = 'UPDATE_ITEM_SETTINGS';
export const CHANGE_STORE_FLAG = 'CHANGE_STORE_FLAG';
